version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

  fastapi:
    build: .
    container_name: fastapi
    restart: on-failure
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command: uvicorn app:app --host 0.0.0.0 --port 5005 --workers 3 --reload

