version: '3'
services:
  fastapi:
    build: .
    container_name: fastapi
    restart: always
    networks:
      - interview_network
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command: uvicorn app:app --host 0.0.0.0 --port 5005 --workers 3 --reload

networks:
  interview_network:
    external:
      name: interview_network